# Generated by Django 5.0.2 on 2024-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="login_image",
        ),
        migrations.AddField(
            model_name="user",
            name="p_image",
            field=models.ImageField(null=True, upload_to="image/"),
        ),
    ]
