# Generated by Django 5.0.2 on 2026-08-05 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blog_vector_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view_duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_views', to='api.owner')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_blogvie_user_id_64e1fa_idx'), models.Index(fields=['blog', '-created_at'], name='api_blogvie_blog_id_26e7a1_idx')],
            },
        ),
    ]
